### ISSUE TITLE
(Main)-Page doesn´t load in Chrome/Chrome based Browsers

### ISSUE THREAD

**Issue by Imipenem** [Imipenem/Project-Peon#5]
The 'index' page (starter page) does not load in Chrome (without Incognito mode) and Brave Browser.
However it DOES load in other browsers like Safari,Edge, Mozilla Firefox.

@Zethson : We should investigate why this is the case (maybe due to some extensions/addons?)

**Comment by Zethson** [comment]
It DOES load on chromium. It's an issue on your end. Maybe you should delete all cookies and such on your machine.

**Comment by Imipenem** [comment]
Closed; it works now without having modified anything.
